//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.05 at 06:50:11 DU CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://code.google.com/p/kickassalternate", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ind.commithook;
