//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.05 at 06:50:11 DU CEST 
//


package com.ind.commithook;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ind.commithook package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ind.commithook
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegexpPattern }
     * 
     */
    public RegexpPattern createRegexpPattern() {
        return new RegexpPattern();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Check.Include }
     * 
     */
    public Check.Include createCheckInclude() {
        return new Check.Include();
    }

    /**
     * Create an instance of {@link CommitHookConfig }
     * 
     */
    public CommitHookConfig createCommitHookConfig() {
        return new CommitHookConfig();
    }

    /**
     * Create an instance of {@link Check.Exclude }
     * 
     */
    public Check.Exclude createCheckExclude() {
        return new Check.Exclude();
    }

    /**
     * Create an instance of {@link Check }
     * 
     */
    public Check createCheck() {
        return new Check();
    }

    /**
     * Create an instance of {@link Check.Parameters }
     * 
     */
    public Check.Parameters createCheckParameters() {
        return new Check.Parameters();
    }

}
